import type { Metadata } from 'next'
import Navigation from '@/components/navigation'
import Providers from '../components/Providers/theme_provider'
import './global.css'
import Header from '@/components/Header'
import AuthSession from '@/components/Providers/session_provider'
export const metadata: Metadata = {
  title: {
    template: '%s | 🎧 NextMusic',
    default: 'Loading',
  },
  description: 'generated by Jeongsu.dev',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AuthSession>
          <Providers>
            <div className="max-w-[1500px] flex justify-center flex-col m-auto">
              <Header />
              <Navigation />
              {children}
            </div>
          </Providers>
        </AuthSession>
      </body>
    </html>
  )
}
